// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEAZ2zXkI71MoZgR5ycGJB1jZM5DIgFg4',
    appId: '1:617475886197:web:a37b1bf7a416159131bc3c',
    messagingSenderId: '617475886197',
    projectId: 'deteksi-2fd96',
    authDomain: 'deteksi-2fd96.firebaseapp.com',
    storageBucket: 'deteksi-2fd96.firebasestorage.app',
    measurementId: 'G-VTB0NESDX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MNWR6_t1NVtII4F2WSBAV1yLegOwq7w',
    appId: '1:617475886197:android:25c4fc1ca544614731bc3c',
    messagingSenderId: '617475886197',
    projectId: 'deteksi-2fd96',
    storageBucket: 'deteksi-2fd96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt8dHmdgjPKCY-1FPt8e-gP0nRJEfi4dc',
    appId: '1:617475886197:ios:c43eb1af24d3abcb31bc3c',
    messagingSenderId: '617475886197',
    projectId: 'deteksi-2fd96',
    storageBucket: 'deteksi-2fd96.firebasestorage.app',
    iosBundleId: 'com.example.deteksiLokasiPalsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt8dHmdgjPKCY-1FPt8e-gP0nRJEfi4dc',
    appId: '1:617475886197:ios:c43eb1af24d3abcb31bc3c',
    messagingSenderId: '617475886197',
    projectId: 'deteksi-2fd96',
    storageBucket: 'deteksi-2fd96.firebasestorage.app',
    iosBundleId: 'com.example.deteksiLokasiPalsu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEAZ2zXkI71MoZgR5ycGJB1jZM5DIgFg4',
    appId: '1:617475886197:web:89932db93de8896c31bc3c',
    messagingSenderId: '617475886197',
    projectId: 'deteksi-2fd96',
    authDomain: 'deteksi-2fd96.firebaseapp.com',
    storageBucket: 'deteksi-2fd96.firebasestorage.app',
    measurementId: 'G-08644ZKR0H',
  );

}